### PR TITLE
Release candidate 2

### PR DESCRIPTION
**Pull request by theotherjimmy**
We know we will need a second release candidate, as a few issues were found with the first one. This pull request, and branch, will collect the updates needed to fix the issues in a second release candidate.

After this pull request is merged, Tag a new releasecandidate with updated release notes.

-----------------

Please add fixes to this list as we find bugs. As we update projects to include fixes, please check them.

# Fixes for the following issues are included.
 - [x] Info command incorrectly shows deviceos-wd status.
 - [x] Maestro segfalt on startup.
 - [x] `upgrade` yeilds `No board detected`
 - [x] Cores 1-3 disabled
 - [x] Missing default gateway route in routing table

### CODE REVIEW

**Comment by SenRamakri** [comment]
@theotherjimmy - Whats blocking us from merging this?
@cmonr - Can we go ahead merge this?

**Comment by theotherjimmy** [comment]
@SenRamakri The fixes section is not finished.

**Comment by SenRamakri** [comment]
@ygoyal18 - Thanks for updating the rc2 with Maestro fix.

**Comment by ygoyal18** [comment]
Created a build with these fixes -http://u203622.usa.arm.com:8080/job/build-gateway-ww-developer/67/ 
Verified all the fixes are working.

**Pull request merged**
