### PR TITLE
Enable more systemd services

### PR DESCRIPTION
**Pull request by theotherjimmy**
# Previously
 - [x] edge-core
 - [x] deviceos-wd
 - [x] maestro

# Now we can also do
 - [x] create-new-eeprom-with-self-signed-certs.sh - named 
       `wait-for-pelion-identity.service`
 - [x] wwrelay-utils - named `wwrelay.service`
 - [x] `do-post-update.service` - was part of the wwrelay startup script.

### CODE REVIEW

**Comment by theotherjimmy** [comment]
Mostly ready. I have to figure out why edge-core is not being restarted correctly

**Comment by theotherjimmy** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=  `Always` does not cause an error, but is incorrect `always` is the correct value :man_facepalming:

**Comment by theotherjimmy** [comment]
@cmonr It's ready.

**Comment by theotherjimmy** [comment]
I confirmed that it boots -> everything is up without intervention. (also, things seem to need to be restarted:
```
root@localhost:~# systemctl show maestro -p NRestarts
NRestarts=7
root@localhost:~# systemctl show edge-core -p NRestarts
NRestarts=3
root@localhost:~# systemctl show wait-for-pelion-identity -p NRestarts
NRestarts=5
root@localhost:~# systemctl show wwrelay -p NRestarts
NRestarts=5
```
)

**Comment by cmonr** [comment]
> https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart= Always does not cause an error, but is incorrect always is the correct value man_facepalming

Ooh, so close.

**Comment by theotherjimmy** [comment]
@cmonr Any hesitation with merging this?

**Pull request merged**
