### PR TITLE
Remove ssl

### PR DESCRIPTION
**Pull request by psppalash**
Changing Devicedb, Devicejs, Relay-term, maestro config so that all services on raspberry Pi can talk through fp-edge.
Tested functionality of relay-term, maestro by running fp-edge on raspberry Pi.
Needs further testing when fp-edge is added to the meta-pelion-edge repo.

### CODE REVIEW

**Comment by psppalash** [comment]
DO NOT MERGE until fp-edge service is added to meta-pelion-edge.

**Comment by ygoyal18** [comment]
@psppalash could you rebase to dev and then open a PR going into dev. This feature is not part of 2.0.0-rc1 so should not be based on that.

**Comment by psppalash** [comment]
> @psppalash could you rebase to dev and then open a PR going into dev. This feature is not part of 2.0.0-rc1 so should not be based on that.

Will do that.

**Comment by psppalash** [comment]
Tried Rebasing against Dev but getting too many merge conflicts. Will create a new branch and PR against dev.

**Comment by psppalash** [comment]
Closing this PR. Opened a new PR against dev.

**Pull request closed without merging**
