### PR TITLE
Added firmware update docs

### PR DESCRIPTION
**Pull request by ygoyal18**
1. firmware_update_workflow.md - provide steps on how to perform firmware
update on system running Pelion Edge Yocto image.
1. port_firmware_update.md - Guide to port the Device Management Update client to
systems running Edge Core.

@AnotherButler  FYI, I reused the "Initiate a firmware update campaign" section from https://github.com/ARMmbed/pelion-dm-edge-docs/pull/43

### CODE REVIEW

**Comment by AnotherButler** [comment]
Why are we duplicating content, and why are we creating content in this repo instead of in the public docs repo?

**Comment by ygoyal18** [comment]
@AnotherButler Sure, we can move the content there. I wasn't aware of the process. So raise a PR against master? Also I am not sure of the folder structure and in which folder these docs should reside in. Should I consult you before raising the PR?

**Comment by AnotherButler** [comment]
@ygoyal18 Thanks. Yes, please raise a PR against master. Feel free to put them loose on the main level or in a folder on the main level. (We'll create a new book for updating.)

**Comment by ygoyal18** [comment]
@AnotherButler Created PR in the other docs repo. Closing this PR.

**Pull request closed without merging**
